# Generated by Django 3.0.8 on 2020-08-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stcok',
            new_name='stock',
        ),
    ]
